//
// Created by mac on 06.07.2026.
//

#ifndef TASK_FOR_EDUCATIONAL_PRACTICE_GRAPH_H
#define TASK_FOR_EDUCATIONAL_PRACTICE_GRAPH_H


class Graph {
};


#endif //TASK_FOR_EDUCATIONAL_PRACTICE_GRAPH_H
